apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: ${namespace}
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort