spring:
  application:
    name: auth-service

server:
  port: 4005

logging:
  level:
    root: info
  pattern:
    correlation: "[${spring.application.name},%X{traceId:-},%X{spanId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    enable:
      kafka: true
    tags:
      application: auth-service
      environment: dev
  prometheus:
    metrics:
      export:
        enabled: true
  observations:
      key-values:
          application: auth-service