spring:
  application:
    name: auth-service

server:
  port: 4005

logging:
  level:
    root: info
  pattern:
    console: "[${spring.application.name},%X{traceId:-},%X{spanId:-}] %-5level %logger{36} - %msg%n"

# --- Tempo Tracing Only ---
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0   # 100% sample, adjust in production
  otlp:
    tracing:
      endpoint: http://tempo:4317  # Tempo OTLP gRPC endpoint

  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always