version: '3.8'

services:
  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    image: patient-service:latest
    container_name: patient-service
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_DATASOURCE_URL=jdbc:postgresql://patient-service-db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INT_MODE=always
#      - Check the src/main/java/app/grpc/BillingServiceGrpcClient.java
      - BILLING_SERVICE_ADDRESS=billing-service
      - BILLING_SERVICE_GRPC_PORT=9001
    ports:
      - "8081:8080"
    networks:
      - internal

  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret
    networks:
      - internal

  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    image: billing-service:latest
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal

networks:
  internal:
#    It has to exist for the services to communicate
    external: true