server:
  port: 4004

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: http://auth-service:4005
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=2

            - id: patient-service-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1
                - JwtValidation

            - id: api-docs-patient-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api-docs/patient-service/**
              filters:
                - RewritePath=/api-docs/patient-service/(?<segment>.*), /v3/api-docs/${segment}
                - RewritePath=/api-docs/patient-service, /v3/api-docs

            - id: api-docs-patient-root
              uri: http://patient-service:4000
              predicates:
                - Path=/api-docs/patient-service
              filters:
                - RewritePath=/api-docs/patient-service, /v3/api-docs

            - id: billing-service-route
              uri: http://billing-service:4001
              predicates:
                - Path=/api/billing/**
              filters:
                - StripPrefix=1

            - id: billing-service-root
              uri: http://billing-service:4001
              predicates:
                - Path=/api/billing
              filters:
                - StripPrefix=1

            - id: analytics-service-route
              uri: http://analytics-service:4002
              predicates:
                - Path=/api/analytics/**
              filters:
                - StripPrefix=1

            - id: analytics-service-root
              uri: http://analytics-service:4002
              predicates:
                - Path=/api/analytics
              filters:
                - StripPrefix=1

            - id: patient-health
              uri: http://patient-service:4000
              predicates:
                - Path=/health/patient/**
              filters:
                - RewritePath=/health/patient/(?<segment>.*), /actuator/${segment}

            - id: billing-health
              uri: http://billing-service:4001
              predicates:
                - Path=/health/billing/**
              filters:
                - RewritePath=/health/billing/(?<segment>.*), /actuator/${segment}

            - id: analytics-health
              uri: http://analytics-service:4002
              predicates:
                - Path=/health/analytics/**
              filters:
                - RewritePath=/health/analytics/(?<segment>.*), /actuator/${segment}

            - id: gateway-actuator
              uri: http://localhost:4004
              predicates:
                - Path=/actuator/**
