{
 "title": "simple-dashboard",
 "tags": [
  "healthcare",
  "microservices",
  "spring-boot"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "ServiceHealthOverview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ServiceHealthStatus",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"spring-boot-services\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "ApplicationPerformanceMetrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPUUsage%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"spring-boot-services\"}[5m])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVMHeapMemoryUsage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\",job=\"spring-boot-services\"}",
     "legendFormat": "{{instance}}-HeapUsed"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\",job=\"spring-boot-services\"}",
     "legendFormat": "{{instance}}-HeapMax"
    }
   ]
  },
  { "title": "ApplicationLogs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "ApplicationLogs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "{container_name=~\"patient-service|billing-service|auth-service|analytics-service|api-gateway\"}|=``"
    }
   ]
  }
 ]
}