#services:
#  postgres:
#    image: postgres:15
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: your-db
#      POSTGRES_USER: your-user
#      POSTGRES_PASSWORD: your-pass
#
#  patient-service:
#    image: patient-service:0.0.1-SNAPSHOT
#    ports:
#      - "12345:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/your-db
#      SPRING_DATASOURCE_USERNAME: your-user
#      SPRING_DATASOURCE_PASSWORD: your-pass
