spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database:
    open-in-view: false
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  sql:
    init:
#      Checks the structure if it changed even with update as the ddl
      mode: always

logging:
  level:
    root: info

server:
  port: 4000
