spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database:
    open-in-view: false
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  sql:
    init:
      mode: always
  #     Inhibits the creation of tables based on entities
  #      mode: never
  jackson:
    date-format: yyyy-MM-dd
    time-zone: UTC

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    root: info

server:
  port: 8080
