apiVersion: 1

datasources:
  - name: DS_PROMETHEUS
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: false

#TODO: Cred ca trebuie adaugat si uid sa fie asa
  - name: DS_LOKI
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
