apiVersion: 1

datasources:
  - name: DS_PROMETHEUS
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: DS_TEMPO
    type: tempo
    uid: tempo
    url: http://tempo:3100
    access: proxy
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['application', 'traceId']
        filterByTraceID: true
        filterBySpanID: true
      tracesToMetrics:
        datasourceUid: 'prometheus'
        tags: ['application']
      serviceMap:
        datasourceUid: 'prometheus'

  - name: DS_LOKI
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
