spring:
  application:
    name: analytics-service

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
logging:
  level:
    root: info
  pattern:
    correlation: "[${spring.application.name},%X{traceId:-},%X{spanId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    enable:
      kafka: true
    tags:
      application: patient-service # change per service
      environment: dev
  prometheus:
    metrics:
      export:
        enabled: true
  observations:
    key-values:
      application: patient-service