spring:
  application:
    name: analytics-service

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      kafka: true
    tags:
      application: patient-service # change per service
      environment: dev
  prometheus:
    metrics:
      export:
        enabled: true
